### ISSUE TITLE
East & West Coast Style

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/contributing#18]
Just an little interesting observation: We are using east coast style for all `{}` bodies but west-coast style for all other `<>` and `()` brackets:
```C++
template<
     typename T_Bar,
     typename T_Foo
 >
 // ...
 ;
 
 // template function specialization
 template< >
 auto
 foo<
     int,
     float
 >(
     int const & extent,
     float & buf
 )
 -> mem::view::foo::detail::Bar<
     int,
     float
 >
 {
 // ...
 }
```

The current reasoning is, that `{}` are used **large** code groups according to @psychocoderHPC. I am ok with that.

**Comment by theZiz** [comment]
I myself would prefer the option to fuse a
```C++
>
{
```
to
```C++
>{
```
although I am a big fan of the east coast style.

**Comment by ax3l** [comment]
I know, the only thing is that it will loose readability with unary template arguments, see:
```C++
 template< >
 auto
 foo<
     int,
     float
 >(
     int const & extent,
     float & buf
 )
 -> mem::view::foo::detail::Bar< justOne > {
     // ...
 }
```

that's why we will keep it for `{}` which can of the length of full pages for scrolling.

**Comment by theZiz** [comment]
Well, I would just not use it for unary template arguments, but starting with binary. :shipit:

**Comment by ax3l** [comment]
yeah, but too special to define. no linter will help us with that, bracket types are easier to differentiate.
