### ISSUE TITLE
Comments in macros

### ISSUE THREAD

**Issue by theZiz** [ComputationalRadiationPhysics/contributing#29]
The proposed way of commenting macros in chapter 8 will not work:
```C++
#define MY_MACRO( )                                                           \
    template<                                                                 \
        // typename T0, ..., typename TN                                      \
        BOOST_PP_ENUM_PARAMS( N, typename T )                                 \
    >                                                                         \
    HDINLINE                                                                  \
    void                                                                      \
    //         ( T0 const, ... , TN const           )                         \
    operator( )( BOOST_PP_ENUM_PARAMS( N, T const ) ) const
```
`//` will start a comment for the rest of the line. However as macros use `\` the whole code above is just one line. So everything after `// typename T0, ..., typename TN` will be ignored. :wink: Even the github highlighting shows the behaviour! :laughing: 

Which way of commenting should be favoured instead? Just plain old `/* … */` ?

**Comment by ax3l** [comment]
Hm, I guess it's `/* ... */` then ;)

Great we don't need much of `BOOST_PP` with variadics in C++11 anymore...

**Comment by theZiz** [comment]
Will do so, but wanted to ask for the right™ way of commenting first. :wink:

**Comment by ax3l** [comment]
@psychocoderHPC agreed?

**Comment by psychocoderHPC** [comment]
ack

**Comment by ax3l** [comment]
@theZiz the stage is yours

**Comment by theZiz** [comment]
Hm, I thought I already made a PR, something went wrong...
