### ISSUE TITLE
Update to clang-format 12

### ISSUE THREAD

**Issue by bernhardmgruber** [ComputationalRadiationPhysics/contributing#49]
clang-format 12 was released so we can update the .clang-format file here.

**Comment by psychocoderHPC** [comment]
Are distribution packages already available too?

**Comment by bernhardmgruber** [comment]
Windows is available since a few days :) Ubuntu 21.04 has it, and it will be released in 2 days :D

I guess the answer is no for a lot of distros.

**Comment by SimeonEhrig** [comment]
For Debain based systems, the ppa is available: https://apt.llvm.org/
The spack package is also available.
