### ISSUE TITLE
new line after semicolon but not if it's in a for loop?

### ISSUE THREAD

**Issue by tu-maurice** [ComputationalRadiationPhysics/contributing#6]
It might be obvious that the statement _semicolon ; is always followed by a new line_ doesn't target the semicolons in the head of a for loop, but as there is a slight logical conflict between the global rule  _there_ **_must**_ _be a new line after semicolon_ and for loop's  _complex parameter_ **_can**_ _be placed on seperate lines_ it would not hurt to mention that the semicolons in a for loop are the exception.

P.S.: I'm not sure if thats a typo or not but in the naming oc-token it says toke instead of tokens.

**Comment by psychocoderHPC** [comment]
Thanks that you point out the inconsistency in the rules. I will create a pull request with an update.

**Comment by sbastrakov** [comment]
Should this issue be closed now? I've added this case as an exception to the global rule (6680623 and 706fe48)

**Comment by ax3l** [comment]
yes, implemented with #28! Thanks for the report! :)
