### ISSUE TITLE
CUDA Kernel <<< >>>

### ISSUE THREAD

**Issue by ax3l** [ComputationalRadiationPhysics/contributing#7]
CUDA Kernel `<<<` and `>>>` should stay without spaces in between.

Reason one: llvm-cuda does not understand spaces in it.
Reason two: it's _one_ fixed syntax element for CUDA and not three template brackets (even if nvcc understands spaces in it)

**Comment by mxmlnkn** [comment]
Does this mean >any< spaces or only directly after <<< and before >>>?

    kernel<<<nBlocks,nThreads,sharedMemSize,stream>>>

vs.

    kernel<<<nBlocks, nThreads, sharedMemSize, stream>>>

**Comment by ax3l** [comment]
I mean the spaces inside `<<<`; writing `< < <` or `<< <` or `< <<` ... causes problems

**Comment by mxmlnkn** [comment]
Oh I understand. Who would do that ...

**Comment by ax3l** [comment]
Well, currently the rules could be interpreted that way with a too simple parser that adds spaces after/before `<`/`>`.
