### ISSUE TITLE
Indentation of innermost namespace

### ISSUE THREAD

**Issue by mxmlnkn** [ComputationalRadiationPhysics/contributing#8]
https://github.com/ComputationalRadiationPhysics/contributing/blob/master/codingGuideLines/cpp.md section 6 points out, that the innermost code in namespaces should be indented (by 4 spaces). Furthermore namespaces are always forced (section 2).

I think this global indent of 4 spaces is problematic.
I vote that the innermost namespace doesn't have to be indented. Or at least not for definitions. For the declarations in .hpp/.h it may be ok, because ideally it would only encompass short function headers. Although in PiConGPU many inline functions are used.

Most of the files I looked at in PiConGPU also ignore the indentation of the innermost namespace.

https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/src/picongpu/include/particles/ionization/ionization.hpp
https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/src/libPMacc/include/math/Tuple.hpp
https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/src/libPMacc/include/mappings/simulation/Selection.hpp
https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/src/picongpu/include/particles/shapes/PCS.hpp
https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/src/picongpu/include/algorithms/DifferenceToLower.hpp
https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/src/picongpu/include/algorithms/Gamma.hpp
https://github.com/ComputationalRadiationPhysics/picongpu/blob/master/src/picongpu/include/fields/FieldManipulator.hpp

**Comment by ax3l** [comment]
> I vote that the innermost namespace doesn't have to be indented

Just to clarify your wordings: it is *not* the innermost `namespace {}` that is indented but the `code` *within* it.

> Most of the files I looked at in [...]

irrelevant.

> back to topic

I think it helps reading the code when one indents the actual code when all the namepace wrapping is done. as an example, just think about declaring a plain function and it's opening/closing `{}` within the namespaces. this should define a directly readable hierarchy lvl.

**Comment by psychocoderHPC** [comment]
closed @ax3l  gave a good description in the comment before
